name: GraviTree
main: me.ryanhamshire.GraviTree.GraviTree
version: 3.5.0
authors: [Big_Scary, ShaneBee]
api-version: 1.13
commands:
  treesfall:
    description: Toggles tree blocks falling when a tree is chopped.
    usage: /TreesFall
  gravitree:
    description: Reload config
    usage: /gravitree reload
    permission: gravitree.reload
permissions:
  gravitree.chop:
    description: Grants permission to apply gravity to chopped trees.
    default: op
  gravitree.reload:
    description: Grants permission to reload config
    default: op
